### ISSUE TITLE
Module found, but go to definition is not working

### ISSUE THREAD

**Issue by sandoche** [ikigeg/awilix-vscode-container-definitions#1]
It says module founds, and I said I want to add automatically the services.
But when I clic to go to the definition of a service it does not work.
Also I am using TypeScript.

**Comment by ikigeg** [comment]
Hey @sandoche sorry for the delayed response! I haven't actually tried the app in a typescript project, can you confirm the filename you are using to setup your container? Typically, in my use cases, i have a single `src/container.js` file, which serves as the start point for the plugin.

**Comment by sandoche** [comment]
I tried with a `container.ts` file.
The extension sent me a notification saying that it found the file. But still after the go-to didn't work.

**Comment by ikigeg** [comment]
Hi @sandoche I just published a new version of the extension, with the teeny fix required to allow it to work for typescript. If you restart vscode it should pick up the latest version, and it will hopefully start working for you. Have a try and let me know 😃

**Comment by sandoche** [comment]
Hi @ikigeg thanks for the answer and your effort.

After setting up `"awilix.containerFile": "servicesContainer.ts"` (the file is in `src/services` I managed to make it partly work.
But it does not jump to the definition of the file but only to the container.

![image](https://user-images.githubusercontent.com/3635348/71680215-ca898100-2d89-11ea-80e8-c5c24919ba80.png)

On the left the current file where I clicked for the definition, on the right the name of the file where I clicked and the name of the file. It doesn't go the the original file. Not that this service is defined as `asValue` in the container.

**Comment by ikigeg** [comment]
Excellent glad to hear it helped, and at the moment that is the expected behaviour. This is an early version of the extension, and will be aiming to extend it in the coming months. Will keep you posted 😊 hope it at least helps in the meantime!

**Comment by sandoche** [comment]
Thanks, good to know!
